name: Keep Streamlit App Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/07 * * * *"
  workflow_dispatch:  # permet aussi de le lancer manuellement

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://autocallablespricer.streamlit.app

