name: Keep Streamlit App Alive

on:
  schedule:
    # Run every 6 hours
    - cron: "*/10 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app
        run: |
          curl -s https://autocallablespricer.streamlit.app/ > /dev/null
